package com.tanjarine.automation.constants;

/**
 * Created by ypolshchykau on 28.11.2014.
 */
public class HardcodedDataForAutomation {

    public final static String PART_OF_MENU_CATEGORY_NAME = "automation_category ";

    public final static String PART_OF_MENU_CATEGORY_DESCRIPTION = "automation_description_for category created. For " +
            "testing purposes only. Submitted: ";

    public final static String COMMON_MENU_FOOTER_TEXT_AREA_DESCRIPTION="this footer was created by automation\n";

    public final static String PART_OF_SUBCATEGORY_NAME="automation_subcategory_";

    public final static String PART_OF_SUBCATEGORY_DESCRIPTION="automation_description_for subcategory added. For " +
            "testing purposes only. Submitted: ";


//   new menu item layout; some desciption for inputs
    public final static String PART_OF_MODULE_DESCRIPTION="Module description added by automation script.  For item-   ";
    public final static String PART_OF_DETAILED_DESCRIPTION="Detailed description added by automation script.  For item-   ";
    public final static String INGREDIENTS="apple\nlimon\nsalt\nbear\nbread\nbutter, etc\n. NOTE: generated by" +
            "selenium sctipt: ";



//    automation game collections naming:
    public final static String GAME_COLLECTION_NAME="AutomationTest";
    public final static String GAME_COLLECTION_DESCRIPTION="collection test description  created by automation test";




//    promotions page:   path name to file for uploading
    public final static String FILE_PATH_TO_PROMOTION_IMAGE = "C:\\Selenium\\test.png";

    public final static String MARKER_BASED_PROMO_NAME ="testMarkerBasedPromo";
    public final static String CAMPAIGN_PROMO_NAME ="testCampaignPromo";
    public final static String DASHBOARD_PROMO_NAME="testDashboardPromo";



//    menu 3.0 create new item layout   hardcoded data for automation
    public final static String NEW_ITEM_NAME_TEMPLATE="item_withModif_";


//    login page test data: empty user, empty password, wrong user, wrong password

    public final static String LOGIN_PAGE_EMPTY_LOGIN ="";
    public final static String LOGIN_PAGE_EMPTY_PASSWORD="";
    public final static String LOGIN_PAGE_WRONG_LOGIN ="abracadabra";
    public final static String LOGIN_PAGE_WRONG_PASSWORD="abracadabra";



//    on finished test suite execution  message
    public final static String ON_TEST_SUITE_EXEC_FINISH_MSG=" TEST SUITE execution FINISHED at ";

}
